### ISSUE TITLE
Do i need to be running a full node?

### ISSUE THREAD

**Issue by adamnmcc** [vipnode/vipnode#15]
Hi, quick question, Do i need to be running a full node i.e. --syncmode "full", or will a fast sync suffice?

I'm trying to get my node up to sync, but its been running a week so far and at current rates i've got another 10 days to go until its fully synced up.. Just wondering if i can save my self some time by using a Fast sync.. 
![geth-sync2](https://user-images.githubusercontent.com/2370463/53343584-9727cb80-3908-11e9-99d4-c070b54eb528.PNG)

**Comment by shazow** [comment]
A fast-sync'd full node is still a full node, so you're good either way! :)

Basically anything that is capable of serving other peers works as a host for vipnode.
