### ISSUE TITLE
Can't find RPC Path

### ISSUE THREAD

**Issue by chris-remus** [vipnode/vipnode#19]
Hi, 

I'm running geth on Ubuntu 18.04 w/this command - 

/usr/bin/geth --cache 256 --maxpeers 50 --syncmode light --rpc --rpcapi db,eth,net,web3 --ws --wsorigins *

Then tried to run -

./vipnode client -vv

And received this output/error - 

2019-04-10 15:04:04.822 INFO Connecting to Ethereum node: /home/liveuser01/.ethereum/geth.ipc
client failed: dial unix /home/liveuser01/.ethereum/geth.ipc: connect: no such file or directory
 -> Could not find the RPC path of the running Ethereum node (such as Geth or Parity). Tried "/home/liveuser01/.ethereum/geth.ipc". Make sure your node is running with RPC enabled. You can specify the path with the --rpc="..." flag.

Please advise on how to fix this. Thank you!

**Comment by shazow** [comment]
Hi there, are you running vipnode under the same user as the geth process?

Are you able to find the geth.ipc unix socket for your geth node?

**Comment by shazow** [comment]
Let me know if you're still having problems.
