### ISSUE TITLE
Please switch your wallet from homestead to Rinkeby.

### ISSUE THREAD

**Issue by gilesbradshaw** [vipnode/vipnode#20]
at vipnode/pool i get

Please switch your wallet from homestead to Rinkeby.
Failed to load client balance.
Failed to load pool status: No account detected, please unlock your wallet first.

**Comment by shazow** [comment]
@gilesbradshaw The current pool contract is on Rinkeby. So you need to switch your wallet network to Rinkeby before it would work. Let me know if you're having any more troubles!
