### ISSUE TITLE
Broken compatibility with parity

### ISSUE THREAD

**Issue by vdo** [vipnode/vipnode#30]
In [dappnode](https://github.com/dappnode/DAppNode/issues/101), we experienced broken compatibility when upgrading parity from v2.3.8 to v2.4.6

The error log at start:
```
host failed: json: cannot unmarshal object into Go struct field PeerInfo.name of type string
 -> Error type *json.UnmarshalTypeError is missing an explanation. Please open an issue at https://github.com/vipnode/vipnode
```

**Comment by shazow** [comment]
Thanks! I'll investigate this week.

**Comment by shazow** [comment]
@vdo Btw, do you have a few of the log messages before that?

I should be able to reproduce without them, but might save me some time.

**Comment by shazow** [comment]
Actually I am having trouble reproducing this, more information appreciated!

**Comment by shazow** [comment]
@vdo Is this the same bug as https://github.com/vipnode/vipnode/issues/33? If so, we need to get dappnode to use the latest tagged release instead of master.

**Comment by shazow** [comment]
Merging into #33 since it has a bit more info now.
