### ISSUE TITLE
Healthcheck endpoint?

### ISSUE THREAD

**Issue by ryanschneider** [vipnode/vipnode#31]
It'd be nice if vipnode pool had a health check endpoint that could be pinged to know the pool server is still working.  A very simple implementation would be to just add something like:

```golang
if r.URL.Path == "/health" {
  http.Error(w, "active", http.StatusOK)
  return
}
```

Before the `Upgrade` check here: https://github.com/vipnode/vipnode/blob/master/server.go#L34

But one that instead returned any stats about the pool not unlike the data displayed at on [the public status page][(https://vipnode.org/status/) as JSON would be even cooler. :)

**Comment by shazow** [comment]
Right now we have:

```console
$ curl 'https://pool.vipnode.org/' -d '{"method":"pool_status"}'
```

which is the payload that the /status dashboard uses.

I guess for Prometheus and such, a non-JSONRPC2 endpoint would be easier to use.

It would be super easy to add this output for /health

@ryanschneider should it just return the JSON inside the `result` field? Or would it be more useful if it was in a different shape?

**Comment by ryanschneider** [comment]
I think for most service discovery/health systems the content is probably
less important than an easy GET request the returns 200, so I think
including the current result data is plenty.
