### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by diglos** [vipnode/vipnode#50]
Hi,

It would be great if you can provide ARM64 binaries in your official releases. I would like to include Vipnode on Ethereum on ARM images (for NanoPC-T4 and RockPro64). I will release it for Raspberry Pi 2/3/4.

Thanks.

Regards!

**Comment by shazow** [comment]
@diglos Good call, I added a `vipnode-linux_arm64.tgz` to the latest release, let me know if that works for you. I'll also add an arm64 build target for future releases.

**Comment by diglos** [comment]
Fantastic, that was quick!

Thanks!
