### ISSUE TITLE
agent: Limit number of light client connections

### ISSUE THREAD

**Issue by mattharrop** [vipnode/vipnode#69]
Is it possible to limit the number of light clients that VIPnode will connect to a full node?  

I'd like to use a full node, but reserve space for my own use of that node.  eg. if my node has a limit of 100 light clients, I'd like VIPnode to only allow 80, so that I can be sure my own use will not be bumped.

**Comment by shazow** [comment]
If you whitelist your own node (`admin.addTrustedPeer("enode://...")`), it will always be able to connect even if the node is full.

Would that work for you?

**Comment by mattharrop** [comment]
I have local apps that connect to my full node using either ws on 8546 or http on 8545, and I want to make sure they can connect.  My understanding is that adding a TrustedPeer would require that I run a light node that they'd connect to, which would peer with my full node.  I may be confusing issues?

**Comment by shazow** [comment]
If you're using the RPC endpoint, I don't believe those are counted towards the "node count" -- that's just for the devp2p sync protocol.

**Comment by mattharrop** [comment]
VIP clients are exclusively ethereum light nodes that connect on the p2p protocol?  I didn't understand this, I assumed they were clients accessing RPC.

**Comment by shazow** [comment]
Vipnode agents are both full nodes (previously known as hosts) and light nodes (previously known as clients) that connect over the p2p protocol.

We don't do anything with RPC yet, but I have some plans to add a load-balanced RPC endpoint to the pool at some point.

**Comment by mattharrop** [comment]
Okay, thanks for the clarification.  This helps.

**Comment by shazow** [comment]
Awesome. :)
