### ISSUE TITLE
agent: Missing RPC method (parity)

### ISSUE THREAD

**Issue by vdo** [vipnode/vipnode#88]
Vipnode version: v2.3.1
Parity version: v2.5.10

DAppNode package fails at bootstrap with the following error:
```
2019-11-19 09:58:02.110 WARNING This is a pre-release version (dev). It can stop working at any time.
2019-11-19 09:58:02.110 INFO Connecting to Ethereum node: http://ethchain.dappnode:8545
2019-11-19 09:58:02.142 INFO Connecting to remote pool: wss://pool.vipnode.org/
[agent] 2019/11/19 09:58:02 Connected to local parity-full node: enode://xxxxxx@172.33.1.6:30303
[agent] 2019/11/19 09:58:02 Registered on pool: Version vipnode/pool/v2.3
2019-11-19 09:58:02.804 ALERT Message from pool: Welcome to the demo vipnode pool! You can manage your account balance here: https://vipnode.org/pool/?enode=xxxxxxx
[agent] 2019/11/19 09:58:03 Pool update: peers=38 active=0 invalid=1 block=8961776 balance=Balance(, 0 wei)
[agent] 2019/11/19 09:58:03 Requesting more kind="" peers from pool: 3
[agent] 2019/11/19 09:58:03 Received 3 peer candidates from pool.
agent failed: Method not found
 -> Missing a required RPC method. Make sure your Ethereum node is up to date.
```

**Comment by shazow** [comment]
@vdo Interesting, thank you! I'll try to investigate it this week.

**Comment by shazow** [comment]
Some notes on what I discovered:
1. Seems the `parity_addReservedPeer` method is not available by default when parity is run in full node mode? (It does seem to be available when it's in light node mode). Running with `--ipc-apis=all` helps here.
2. Seems that `parity_addReservedPeer` doesn't take just a nodeID for whitelisting anymore? It requires a full enode string with host/port. I need to investigate if this is feasible to work with or if it'll break other things, also need to find the actual change to figure out the motivation behind it.

**Comment by shazow** [comment]
@vdo Heads up, I have a PR open that fixes this, review appreciated: https://github.com/vipnode/vipnode/pull/91
